name: Lab 4

on:
  workflow_dispatch:

env:
  WORKDIR: Theory_and_technologies_of_developing_safe_distribution_systems/lab4//WcfServiceCalc
  SOLUTION: WcfServiceCalc.sln
  CSPROJ: WcfServiceCalc/WcfServiceCalc.csproj
  APP_NAME: khai555smlab4

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore dependencies
      run: nuget restore ${{ env.SOLUTION }}
      working-directory: ${{ env.WORKDIR }}
    - name: Build
      run: msbuild ${{ env.CSPROJ }} -t:Rebuild -p:Configuration=Release /p:OutDir=artifact
      working-directory: ${{ env.WORKDIR }}
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.APP_NAME }}
        slot-name: 'Production'
        package: ${{ env.WORKDIR }}\WcfServiceCalc\artifact\_PublishedWebsites\WcfServiceCalc
        publish-profile: ${{ secrets.LAB4_AZUREAPPSERVICE_PUBLISHPROFILE_PRODUCTION }}
